import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

const GRUVBOX = {
  light: {
    background: '#f9f5d7',
    backgroundAlt: '#f2e5bc',
    backgroundSoft: '#f3eacb',
    foreground: '#3c3836',
    foregroundSoft: '#665c54',
    card: '#fbf1c7',
    cardForeground: '#3c3836',
    popover: '#f2e5bc',
    popoverForeground: '#3c3836',
    primary: '#d79921',
    primaryForeground: '#282828',
    secondary: '#ebdbb2',
    secondaryForeground: '#3c3836',
    muted: '#ebdbb2',
    mutedForeground: '#7c6f64',
    accent: '#d5c4a1',
    accentForeground: '#3c3836',
    destructive: '#cc241d',
    destructiveForeground: '#fbf1c7',
    success: '#98971a',
    successForeground: '#fbf1c7',
    info: '#458588',
    infoForeground: '#fbf1c7',
    border: '#d5c4a1',
    input: '#ebdbb2',
    ring: '#d65d0e',
    shadow: '#3c383633',
    radius: '1.35rem',
  },
  dark: {
    background: '#282828',
    backgroundAlt: '#32302f',
    backgroundSoft: '#3c3836',
    foreground: '#fbf1c7',
    foregroundSoft: '#d5c4a1',
    card: '#32302f',
    cardForeground: '#fbf1c7',
    popover: '#3c3836',
    popoverForeground: '#fbf1c7',
    primary: '#d79921',
    primaryForeground: '#1d2021',
    secondary: '#3c3836',
    secondaryForeground: '#ebdbb2',
    muted: '#504945',
    mutedForeground: '#bdae93',
    accent: '#504945',
    accentForeground: '#fbf1c7',
    destructive: '#fb4934',
    destructiveForeground: '#1d2021',
    success: '#b8bb26',
    successForeground: '#1d2021',
    info: '#83a598',
    infoForeground: '#1d2021',
    border: '#504945',
    input: '#3c3836',
    ring: '#fe8019',
    shadow: '#00000055',
    radius: '1.35rem',
  },
} as const;

export const THEME = GRUVBOX;

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: GRUVBOX.light.background,
      border: GRUVBOX.light.border,
      card: GRUVBOX.light.card,
      notification: GRUVBOX.light.destructive,
      primary: GRUVBOX.light.primary,
      text: GRUVBOX.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: GRUVBOX.dark.background,
      border: GRUVBOX.dark.border,
      card: GRUVBOX.dark.card,
      notification: GRUVBOX.dark.destructive,
      primary: GRUVBOX.dark.primary,
      text: GRUVBOX.dark.foreground,
    },
  },
};
